# MegaLinter Configuration
APPLY_FIXES: all

ENABLE_LINTERS:
  - CPP_CPPLINT
  - CPP_CLANG_FORMAT

DISABLE:
  - COPYPASTE # Disable COPYPASTE checks

# Filter specific rules
FILTER_RULES:
  - build/include_subdir # Disable include subdir warnings

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: true

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true