# MegaLinter Configuration
APPLY_FIXES: all

ENABLE_LINTERS:
  - CPP_CPPLINT
  - CPP_CLANG_FORMAT

DISABLE:
  - COPYPASTE # Disable COPYPASTE checks

# Configure filters for cpplint
LINTER_RULES:
  CPP_CPPLINT:
    filter: "-build/include_subdir  -runtime/references" # Disable include_subdir rule


SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: true

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true