/*
** EPITECH PROJECT, 2024
** RTYPE
** File description:
** events
*/

#ifndef ENGINE_MODULES_DISPLAY_EVENTS_HPP_
#define ENGINE_MODULES_DISPLAY_EVENTS_HPP_


#endif // ENGINE_MODULES_DISPLAY_EVENTS_HPP_
