name: Build on Windows with MSVC and vcpkg

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean up vcpkg directory
        run: if exist vcpkg rmdir /s /q vcpkg
        shell: cmd

      - name: Cache vcpkg dependencies
        uses: actions/cache@v3
        with:
          path: vcpkg/installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg

      - name: Clone vcpkg
        run: git clone https://github.com/microsoft/vcpkg.git
        shell: cmd

      - name: Install vcpkg
        run: |
          cd vcpkg
          .\bootstrap-vcpkg.bat
        shell: cmd

      - name: Install gtest
        run: |
          echo Installing gtest...
          .\vcpkg.exe install gtest:x64-windows --debug
        shell: cmd

      - name: List Installed vcpkg Dependencies
        run: .\vcpkg\vcpkg.exe list
        shell: cmd

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build . --config Release