name: Build on Windows with MSVC and vcpkg

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: vcpkg/installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg

      - name: clone vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install gtest
          ls ..
        shell: cmd

      - name: install vcpkg
        run: |
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install gtest
          dir installed
          dir ..
        shell: cmd

      - name: List Installed vcpkg Dependencies
        run: .\vcpkg\vcpkg.exe list
        shell: cmd

      - name: Debug vcpkg installation
        run: dir vcpkg

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build . --config Release