name: MegaLinter

on:
  push:
  pull_request:
    branches:
      - main
      - master

env:
  APPLY_FIXES: all
  APPLY_FIXES_EVENT: pull_request
  APPLY_FIXES_MODE: commit

permissions:
  contents: write
  pull-requests: write

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global safe.directory /github/workspace
          git config --global user.name "MegaLinter Bot"
          git config --global user.email "megalinter@example.com"

      - name: MegaLinter
        uses: oxsecurity/megalinter/flavors/c_cpp@v8
        id: ml
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Debug MegaLinter Output
        run: |
          echo "Has updated sources: ${{ steps.ml.outputs.has_updated_sources }}"
          echo "Environment Variables:"
          env

      - name: Commit and push applied linter fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        if: >-
          steps.ml.outputs.has_updated_sources == 1 &&
          env.APPLY_FIXES_MODE == 'commit'
        with:
          branch: ${{ github.ref_name }}
          commit_message: "[MegaLinter] Apply linters fixes"
          commit_user_name: megalinter-bot
          commit_user_email: megalinter@example.com

      - name: Create Pull Request with applied fixes
        uses: peter-evans/create-pull-request@v6
        id: cpr
        if: >-
          steps.ml.outputs.has_updated_sources == 1 &&
          env.APPLY_FIXES_MODE == 'pull_request'
        with:
          token: ${{ secrets.PAT }}
          commit-message: "[MegaLinter] Apply linters automatic fixes"
          title: "[MegaLinter] Apply linters automatic fixes"
          branch: linter-fixes/${{ github.sha }}