jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config --global safe.directory /github/workspace
          git config --global user.email "bot@example.com"
          git config --global user.name "MegaLinter Bot"

      - name: MegaLinter
        uses: oxsecurity/megalinter/flavors/c_cpp@v8
        id: ml
        env:
          GITHUB_TOKEN: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          APPLY_FIXES: all

      - name: Debug MegaLinter Output
        run: echo "Updated Sources: ${{ steps.ml.outputs.has_updated_sources }}"

      - name: Commit and Push Fixes
        if: steps.ml.outputs.has_updated_sources == 1
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[MegaLinter] Apply automatic fixes"
          branch: ${{ github.head_ref || github.ref_name }}