name: 'area'

on:
  push:
    branches:
    - main
    - master
  pull_request:
    branches:
    - main
    - master

jobs:
  push_to_mirror:
    if: ${{ github.event_name == 'push' }}
    name: "Push all files to mirror repository"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}