name: Rtype Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: vcpkg/installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build g++ cmake curl zip unzip

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
        id: vcpkg

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -G Ninja
          ninja
        env:
          CXX: /usr/bin/g++
          CC: /usr/bin/gcc

      - name: Run tests
        run: |
          cd build
          ./server/r-type_server_tests
          ./client/r-type_client_tests