name: Rtype Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y g++ cmake curl zip unzip

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
        id: vcpkg

      - name: Configure vcpkg toolchain
        run: echo "::set-output name=toolchain-file::$(pwd)/vcpkg/scripts/buildsystems/vcpkg.cmake"
        id: vcpkg-toolchain

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ steps.vcpkg-toolchain.outputs.toolchain-file }}
          make

      - name: Run tests
        run: |
          cd build
          ./server/r-type_server_tests